name: Java CI

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4.2.2
    - name: Set up JDK 11
      uses: actions/setup-java@v1.4.3
      with:
        java-version: 11
    - name: Build with Maven
      run: mvn package --file pom.xml
